name: Delivery Pipeline

permissions: read-all

on:
  workflow_call:
    inputs:
      build-script:
        description: Name of build script
        type: string
    outputs:
      build_version:
        description: "Build version"
        value: ${{ jobs.build-test-and-push.outputs.build_version }}

concurrency:
  group: ${{ inputs.build-script }}

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.push.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and run unit/integration tests
        run: |
          echo "Running script: $BUILD_SCRIPT"
          sleep 20
        env:
          BUILD_SCRIPT: ${{ inputs.build-script }}
      - name: Setup comoponent test infrastructure
        run: echo Setting up component test infrastructure; sleep 5            
      - name: Running component tests
        run: echo Running component tests; sleep 5
      - name: Pushing Docker Image
        id: push
        run: |
          echo Pushing successfully build image
          export BUILD_VERSION=$(date +'%Y%m%d%H%M%S')_$(git rev-parse --short HEAD)
          echo "::set-output name=version::$BUILD_VERSION"

          
#  static-code-analysis:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Static code analysis
#        run: echo Analysing code; sleep 10
