name: Delivery Pipeline

permissions: read-all

on:
  workflow_call:
    inputs:
      build-script:
        description: Name of build script
        type: string

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and run unit/integration tests
        run: |
          echo "Running script: $BUILD_SCRIPT"
          sleep 5
        env:
          BUILD_SCRIPT: ${{ inputs.build-script }}
      - name: Setup comoponent test infrastructure
        run: echo Setting up component test infrastructure; sleep 5            
      - name: Running component tests
        run: echo Running component tests; sleep 5
      - name: Pushing Docker Image
        run: echo Pushing successfully build image
          
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Static code analysis
        run: echo Analysing code; sleep 10
