name: Delivery Pipeline

permissions: read-all

on:
  workflow_call:

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          docker version
          docker-compose version
          echo Checking out code
          sleep 5            
      - name: Build and run unit/integration tests
        run: echo Building and running tests; sleep 5
      - name: Setup comoponent test infrastructure
        run: echo Setting up component test infrastructure; sleep 5            
      - name: Running component tests
        run: echo Running component tests; sleep 5
      - name: Pushing Docker Image
        run: echo Pushing successfully build image
  
  deploy:
    needs: build-test-and-push
    uses: anders-olofsson/gh-actions-test-shared/.github/workflows/deployment.yaml@main
    with:
      version: ${{ github.sha }}
        
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Static code analysis
        run: echo Analysing code; sleep 10
